# Generated by cucumber-sinatra. (Sun Jul 04 17:52:31 +0100 2010)

require File.join(File.dirname(__FILE__), '..', '..', 'lib/application.rb')

require 'capybara'
require 'capybara/cucumber'
require 'spec'

Application.set(:environment, :test)

World do
  Capybara.app = Application
  include Capybara
  include Spec::Expectations
  include Spec::Matchers
end
